### ISSUE TITLE
D&D 1.2.0 incompatibility

### ISSUE THREAD

**Issue by Sky-Captain-13** [RedReign/FoundryVTT-BetterRolls5e#175]
The variable declarations at line 1389, 1390, and 1391 are causing Better Rolls to silently crash without an error message and not send a card to chat for spells with levels. The lines below are how I changed them to make them work with D&D 1.2.0. These fixes are probably not backwards compatible.
```js
1389: lvl = spellFormData.level;
1390: consume = Boolean(spellFormData.consumeSlot);
1391: placeTemplate = Boolean(spellFormData.placeTemplate);
```

**Comment by Hydrall** [comment]
Having another error in regards to resource consumption, it appears; when a roll is set to consume an attribute or item uses, it pops up:
```
custom-roll.js:1480 Uncaught (in promise) TypeError: item._handleResourceConsumption is not a function
    at CustomItemRoll.consumeCharge (custom-roll.js:1480)
    at CustomItemRoll.roll (custom-roll.js:428)
    at async CustomItemRoll.toMessage (custom-roll.js:624)
```

**Comment by CarlosFdez** [comment]
Can't even rest without something breaking it seems. @Sky-Captain-13 would you happen to find to know of a decent module that does auto deployment that I can steal their deployment/build scheme from? Would like to set something up so small fixes aren't hard for Red to deploy.

**Comment by Sky-Captain-13** [comment]
Yeah, I'm the last person to ask about auto deployment heh. Also, any chance of Red making it so you can approve merge commits and whatever?

**Comment by raiden104** [comment]
This is also an issue for me. Any timeline on a fix/update?

**Comment by hanhmchau** [comment]
Hey, I appreciate all the work you guys have put in. I see that there's already a fix, when is it going to be released?

Also, as an aside: it seems like recently there have been several significant issues that have simple, small fixes already implemented by others (the cantrip scaling, and this one) that take a long time to be released. BR is a key module for many tables and these bugs affect games heavily. Perhaps something could be done to see these changes released quicker. I agree with @Sky-Captain-13, can the repo owner consider allowing another contributor to merge commits?

**Comment by babloe** [comment]
as @hanhmchau says this is debilitating for my dnd campaign I've been using base stuff for almost a week now and I'm waiting very much on a fix

**Comment by ComedianTF2** [comment]
You can find a temporary patch here: https://github.com/CarlosFdez/FoundryVTT-BetterRolls5e/releases/download/v1.2.1.2/module.json

**Comment by Asherlock** [comment]
It's a working patch anyway! Thanks!

**Comment by Moonshaft** [comment]
Making sure I'm doing this correctly. I place the patch json in the following path, correct?: data/modules/betterrolls5e

If so I replaced it then booted up my game to test and I'm still getting the same result of no spells casting.

**Comment by CarlosFdez** [comment]
![image](https://user-images.githubusercontent.com/1286721/102550095-3c3a0800-408b-11eb-86be-115a4d798d54.png)

You put the module.json in the textbox. You may or may not need to remove the BR installation. When this module updates, it will also update to newest BR update version.

**Comment by Moonshaft** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1286721/102550095-3c3a0800-408b-11eb-86be-115a4d798d54.png)
> 
> You put the module.json link in the textbox. You may or may not need to remove the BR installation. When this module updates, it will also update to newest BR update version.

Perfect, I was just being an idiot and doing it wrong. The temp band aide patch seems to work--thank you!

**Comment by RedReign** [comment]
Should be fixed with the update I'm pushing now! Thanks to @CarlosFdez for this.

**Comment by Sky-Captain-13** [comment]
Thanks Red! ^_^
