### ISSUE TITLE
Rolling melee weapons not working

### ISSUE THREAD

**Issue by johnwiesenfeld** [RedReign/FoundryVTT-BetterRolls5e#210]
Haven't been able to test extremely thoroughly, but all 7 of my characters can't roll melee weapons (greataxes, swords etc) after 1.3.5 and 1.3.6 updates. still works on 1.3.4.

Console error reads- Uncaught (in promise) TypeError: item.getAttackToHit is not a function

Screencap of error below, along with the page I'm rolling from on character sheet. 
![Error](https://user-images.githubusercontent.com/43589120/106236050-e63fa080-61b0-11eb-80d1-47e77867bb03.PNG)
![charactersheet](https://user-images.githubusercontent.com/43589120/106236043-e475dd00-61b0-11eb-8c33-9dc1afc643b7.PNG)

**Comment by johnwiesenfeld** [comment]
I'm an idiot. Just updated the 5e game system and it works now. Newbie to foundry, sorry!

**Comment by CarlosFdez** [comment]
@johnwiesenfeld despite that being the case it was still a help. Seems that getAttackToHit() was added in a newer 5e version and I need to update the minimum version required.
